sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) # get the head sha and store in the envvar called SHA
    - COULDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; 
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json  # this is to use the encryped file
  - gcloud config set project multi-k8s-247418  # copy the ID of your project
  - gcloud config set compute/zone us-central1-a # use the compute zone, find it in the kubernetes engine
  - gcloud container clusters get-credentials multi-cluster # the name of your kubernetes cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin
  - docker build -t hhsu15/react-test -f ./client/Dockerfile.dev ./client # build the image
script:
  - docker run -e CI=true hhsu15/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master # only do the deploy when update on master branch

