sudo: required
services:
  -docker

before_install:
  - docker build -t hhsu15/react-rest -f ./client/Dockerfile.dev ./client
 # if you have other test you want to run then you would put them here like so to build the dev image
 
script:
  # the test script here
  - docker run hhsu15/react-rest npm test -- --coverage

after_success:
  - docker build -t hhsu15/multi-client ./client
  - docker build -t hhsu15/multi-nginx  ./nginx/
  - docker build -t hhsu15/multi-server ./server
  - docker build -t hhsu15/multi-worker ./worker
  # log in to the docker CLI
  # similar to the API key, go to travis site and set the environment variable
  # get password via the env var and pass it thru stdin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push to docker hub
  - docker push hhsu15/multi-client
  - docker push hhsu15/multi-nginx
  - docker push hhsu15/multi-server
  - docker push hhsu15/multi-worker
