apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  # a path to reach out to letsencrypt api
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'shinhsu18@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}

