version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  # for the sever image, we will specify build, volumes, and env variables
  nginx:
    # restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'  # nginx uses 80 as default, map to 3050 for us
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules # leave the folder as is
      - ./server:/app # everything else redirect to local folder
    # set the env variables
    environment:
      - REDIS_HOST=redis # name of the service
      - REDIS_PORT=6379 # default port for redis (refer to documentaiton)
      # refer to postgress documentation for default values
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  # specify the client 
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
